[ci] run ut ci using docker container (#62)
* run ut ci using docker container

* run ut ci using docker container

* add branch and line coverage in ut

* add branch and line coverage ci

---------

Co-authored-by: yanhe13 <yanhe13@huawei.com>

diff --git a/.github/workflows/run-ut-on-pr-py.yml b/.github/workflows/run-ut-on-pr-py.yml
--- a/.github/workflows/run-ut-on-pr-py.yml
+++ b/.github/workflows/run-ut-on-pr-py.yml
@@ -19,24 +19,20 @@ env:
   PY310_VERSION: 3.10.12
 jobs:
   pr_run_test:
-    runs-on: [self-hosted, Linux, X64, 66_19]
+    runs-on: [self-hosted, Linux]
     timeout-minutes: 20
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Prepare - Install benchmark
         run: |
-          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/local_bin/python-${PY310_VERSION}/lib"
-          source ${HOME}/virtualenvs/workon310/bin/activate
-          pip3 install -e ./ --use-pep517
-          pip3 install -r requirements/api.txt
-          pip3 install -r requirements/extra.txt
-          pip3 install -r requirements/datasets/bfcl_dependencies.txt --no-deps
+          pip3 install -e ./ -i https://repo.huaweicloud.com/repository/pypi/simple --trusted-host repo.huaweicloud.com --use-pep517
+          pip3 install -r requirements/api.txt -i https://repo.huaweicloud.com/repository/pypi/simple --trusted-host repo.huaweicloud.com
+          pip3 install -r requirements/extra.txt -i https://repo.huaweicloud.com/repository/pypi/simple --trusted-host repo.huaweicloud.com
+          pip3 install -r requirements/datasets/bfcl_dependencies.txt --no-deps -i https://repo.huaweicloud.com/repository/pypi/simple --trusted-host repo.huaweicloud.com
       - name: Run Test
         run: |
-          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/local_bin/python-${PY310_VERSION}/lib"
-          source ${HOME}/virtualenvs/workon310/bin/activate
-          pip3 install pytest pytest-cov pytest-xdist
+          pip3 install pytest pytest-cov pytest-xdist -i https://repo.huaweicloud.com/repository/pypi/simple --trusted-host repo.huaweicloud.com
           python3 tests/run_tests.py tests/UT -p 16
 
       - name: Check Result
@@ -59,17 +55,29 @@ jobs:
             echo "[INFO] All test case passed. "
           fi
           total_coverage=$(cat ${summary_path} | grep "Total coverage" | cut -d' ' -f3 | tr -d '%')
-          if [ $(echo "$total_coverage < 80" | bc) -eq 1 ]; then
-            echo "[ERROR] Code coverage is lower than 80.0%, current coverage is ${total_coverage}%. "
+          if python3 -c "exit(0 if float('$total_coverage') < 80 else 1)"; then
+            echo "[ERROR] Code total coverage is lower than 80.0%, current coverage is ${total_coverage}%. "
             exit 1
           else
-            echo "[INFO] Code coverage is higher than 80.0%, current coverage is ${total_coverage}%. "
+            echo "[INFO] Code total coverage is higher than 80.0%, current coverage is ${total_coverage}%. "
+          fi
+          line_coverage=$(cat ${summary_path} | grep "Line coverage" | cut -d' ' -f3 | tr -d '%')
+          if python3 -c "exit(0 if float('$line_coverage') < 80 else 1)"; then
+            echo "[ERROR] Code line coverage is lower than 80.0%, current coverage is ${line_coverage}%. "
+            exit 1
+          else
+            echo "[INFO] Code line coverage is higher than 80.0%, current coverage is ${line_coverage}%. "
+          fi
+          branch_coverage=$(cat ${summary_path} | grep "Branch coverage" | cut -d' ' -f3 | tr -d '%')
+          if python3 -c "exit(0 if float('$branch_coverage') < 60 else 1)"; then
+            echo "[ERROR] Code branch coverage is lower than 60.0%, current coverage is ${branch_coverage}%. "
+            exit 1
+          else
+            echo "[INFO] Code branch coverage is higher than 60.0%, current coverage is ${branch_coverage}%. "
           fi
       - name:  Uninstall benchmark
         if: always()
         run: |
-          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/local_bin/python-${PY310_VERSION}/lib"
-          source ${HOME}/virtualenvs/workon310/bin/activate
           pip3 uninstall ais_bench_benchmark -y
           if [ $? -ne 0 ]; then
             echo "[ERROR] Uninstall benchmark failed. "
